################################################################################
#                                                                              #
#                                                                              #
#                        Application Docker Development                        #
#           NOTE:  Check .env file for necessary fields to modify to           #
#                           secure this installation                           #
#                                                                              #
#                                                                              #
################################################################################
name: application_dev
networks:
    app-tier:
        driver: bridge
volumes:
    dbDevData:
    redisDevData:

services:
    # Application Container
    application:
        container_name: application
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./application
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        # depends_on:
        #     database:
        #         condition: service_healthy

    # NGINX Web Server
    nginx:
        container_name: nginx
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ../docker/nginx
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        ports:
            - "80:80"
            - "443:443"
        networks:
            - app-tier
        # depends_on:
        #     database:
        #         condition: service_started
        #     reverb:
        #         condition: service_started

    # Reverb Container for Websockets
    reverb:
        container_name: reverb
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./application
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ['php', '/var/www/html/artisan', 'reverb:start']
        # depends_on:
        #     tech_bench:
        #         condition: service_healthy

    # Horizon Container to run background jobs
    horizon:
        container_name: horizon
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./application
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ["php", "/var/www/html/artisan", "horizon"]
        # depends_on:
        #     tech_bench:
        #         condition: service_healthy
        #     nginx:
        #         condition: service_healthy

    # Scheduler Container
    scheduler:
        container_name: scheduler
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./application
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        command: ["php", "/var/www/html/artisan", "schedule:work"]
        # depends_on:
        #     tech_bench:
        #         condition: service_healthy
        #     nginx:
        #         condition: service_healthy

    #  MySQL Database Container
    database:
        container_name: database
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ../docker/database
            dockerfile: Dockerfile
        environment:
            - MYSQL_ROOT_PASSWORD=tbRootPasswd
        volumes:
            - dbDevData:/var/lib/mysql
            - ./database/testDatabase.sql:/docker-entrypoint-initdb.d/testDatabase.sql
        networks:
            - app-tier
        ports:
            - "3306:3306"

    #  Redis Container for Cache, Job and Email Queuing
    redis:
        container_name: redis
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ../docker/redis
            dockerfile: Dockerfile
        environment:
            - REDIS_PASSWORD=tbRootPassword
        volumes:
            - redisDevData:/data
        networks:
            - app-tier
        ports:
            - "6379:6379"

    ###########################################################################################
    #                               Dev Specific Containers                                   #
    ###########################################################################################

    #  Mailpit for Email Traps
    mailpit:
        image: axllent/mailpit:latest
        container_name: mailpit
        restart: unless-stopped
        stop_signal: SIGTERM
        networks:
            - app-tier
        ports:
            - "8025:8025"
            - "1025:1025"

    #  NPM Container to run npm run dev
    npm:
        container_name: npm
        restart: unless-stopped
        stop_signal: SIGTERM
        build:
            context: ./application
            dockerfile: Dockerfile
        volumes:
            - ../src:/var/www/html
            - ./.env:/var/www/html/.env
        networks:
            - app-tier
        ports:
            - "5173:5173"
        command: npm run dev
        # depends_on:
        #     tech_bench:
        #         condition: service_healthy
        #     nginx:
        #         condition: service_healthy
